name: Test Deploy

on:
  push:
    branches:
      - "test-deploy-timothy"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - run: |
        npx npm-cli-login -y
        npm publish .github/cli-7.16.4-test.tgz --registry https://zowe.jfrog.io/zowe/api/npm/npm-local-release/
      env:
        NPM_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
        NPM_PASS: ${{ secrets.ARTIFACTORY_PASSWORD }}
        NPM_EMAIL: ${{ secrets.ZOWE_ROBOT_EMAIL }}
        NPM_REGISTRY: "https://zowe.jfrog.io/zowe/api/npm/npm-local-release"
        NPM_SCOPE: "@zowe"
