name: Test Deploy

on:
  push:
    branches:
      - "test-deploy-timothy"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - run: |
        cd /tmp
        npx npm-cli-login -y
        curl -o cli-old.tgz https://zowe.jfrog.io/artifactory/npm-local-release/%40zowe/cli/-/%40zowe/cli-7.16.4.tgz
        tar -xzf cli-old.tgz
        cd package && npm version 7.1.4 && npm install && cd ..
        tar -czf cli-new.tgz package
        npm publish cli-new.tgz --registry https://zowe.jfrog.io/zowe/api/npm/npm-local-release/ --tag test
      env:
        NPM_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
        NPM_PASS: ${{ secrets.ARTIFACTORY_PASSWORD }}
        NPM_EMAIL: ${{ secrets.ZOWE_ROBOT_EMAIL }}
        NPM_REGISTRY: "https://zowe.jfrog.io/zowe/api/npm/npm-local-release"
        NPM_SCOPE: "@zowe"
